import { describe, expect, it } from 'vitest';
import { discoverWallets, disconnectedAfterReload, initialWalletState, mergeWallet, validSession, walletName, walletReducer } from './wallet';
describe('wallet boundary', () => {
  const p={request:async()=>null};
  it('selects only supported EIP-6963 providers and deduplicates',()=>{const x=discoverWallets([{info:{name:'MetaMask'},provider:p},{info:{name:'OKX Wallet'},provider:p},{info:{name:'Other'},provider:{request:async()=>null}}]);expect(x).toHaveLength(1);expect(walletName(x[0])).toBe('MetaMask')});
  it('renders at most one callable provider for each supported wallet',()=>{const a={request:async()=>null},b={request:async()=>null};const x=discoverWallets([{info:{name:'OKX Wallet'},provider:a},{info:{rdns:'com.okx.wallet'},provider:b}]);expect(x).toHaveLength(1);expect(x[0].provider).toBe(a)});
  it('replaces only the matching legacy wallet after a late announcement',()=>{const legacy={request:async()=>null},announced={request:async()=>null},rabby={request:async()=>null};const before=[{info:{name:'OKX Wallet'},provider:legacy},{info:{name:'Rabby'},provider:rabby}];const after=mergeWallet(before,{info:{name:'OKX Wallet',uuid:'okx'},provider:announced});expect(after).toHaveLength(2);expect(after.find(x=>walletName(x)==='OKX Wallet')?.provider).toBe(announced);expect(after.find(x=>walletName(x)==='Rabby')?.provider).toBe(rabby)});
  it('keeps connection truth in one atomic state',()=>{const item={info:{name:'Rabby'},provider:p};let state=walletReducer(initialWalletState,{type:'DISCOVER',wallets:[item]});state=walletReducer(state,{type:'OPEN'});expect(state.phase).toBe('CHOOSER_OPEN');state=walletReducer(state,{type:'CONNECT',wallet:item});expect(state.phase).toBe('CONNECTING');state=walletReducer(state,{type:'CONNECTED',wallet:item,kind:'Rabby',account:('0x'+'1'.repeat(40)) as `0x${string}`});expect(state).toMatchObject({phase:'CONNECTED',kind:'Rabby'});expect(state.account).toHaveLength(42);state=walletReducer(state,{type:'WRONG_CHAIN',message:'wrong'});expect(state).toMatchObject({phase:'WRONG_CHAIN',account:null,error:'wrong'})});
  it('starts disconnected after reload',()=>expect(disconnectedAfterReload()).toBeNull());
  it('rejects wrong chain and malformed account',()=>{expect(validSession({kind:'MetaMask',account:'0x1',chainId:'0xf22d'})).toBe(false);expect(validSession({kind:'MetaMask',account:'0x'+'1'.repeat(40),chainId:'0xf22f'})).toBe(false)});
});
